//channels

export const FETCH_CHANNELS_REQUEST = 'FETCH_CHANNELS_REQUEST'
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS'
export const FETCH_CHANNELS_ERROR = 'FETCH_CHANNELS_ERROR'
export const ADD_CHANNEL = 'ADD_CHANNEL'
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL'
export const UPDATE_CHANNEL = 'UPDATE_CHANNEL'